name: Build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ master ]

env:
  Z3_VERSION: 4.8.8
  BOOGIE_NO_GITVERSION: 1
  BOOGIE_BRANCH: c9755c964cb598ed

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Get Z3 – Ubuntu
        run: |
          wget https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/z3-${Z3_VERSION}-x64-ubuntu-16.04.zip
          unzip z3-*.zip
          echo $(find $PWD/z3* -name bin -type d)>> $GITHUB_PATH
        if: matrix.os == 'ubuntu-latest'

      - name: Get Z3 – MacOS
        run: |
          wget https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/z3-${Z3_VERSION}-x64-osx-10.14.6.zip
          unzip z3-*.zip
          echo $(find $PWD/z3* -name bin -type d) >> $GITHUB_PATH
        if: matrix.os == 'macos-latest'

      - name: Get Z3 – Windows
        run: |
          curl https://github.com/Z3Prover/z3/releases/download/z3-${Z3_VERSION}/z3-${Z3_VERSION}-x64-win.zip -Lo z3-x64-win.zip
          unzip z3-*.zip
          echo $(find $PWD/z3* -name bin -type d) >> $GITHUB_PATH
        if: matrix.os == 'windows-latest'
        shell: bash
        
      - name: Install Python tools for testing
        run: |
          pip3 install setuptools
          pip3 install lit OutputCheck pyyaml psutil
        shell: bash

      - name: Get repo
        run: |
          git clone https://github.com/boogie-org/boogie.git
          cd boogie
          git checkout $BOOGIE_BRANCH
        shell: bash

      - name: Compile Boogie, run unit tests
        run: |
          cd boogie
          dotnet build -c Release Source/Boogie.sln
          dotnet test -c Release Source/Boogie.sln
        shell: bash
      - name: Run Boogie tests - Linux and MacOS
        run: |
          cd boogie
          lit -v --timeout=120 -D configuration=Release Test
          # remove bin folder
          rm -rf Source/BoogieDriver/bin
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        shell: bash        
      - name: Run Boogie tests - Windows
        run: |
          cd boogie
          # provide the z3 path hardcoded (PATH change does not work)
          lit -v --timeout=120 -D configuration=Release -D "boogie_params=/proverOpt:PROVER_PATH=D:\a\boogie-builder\boogie-builder\z3-4.8.8-x64-win\bin\z3.exe" Test
          # remove bin folder
          rm -rf Source/BoogieDriver/bin
        if: matrix.os == 'windows-latest'
        shell: bash
      - name: Build standalone version – Ubuntu
        run: |
          cd boogie
          dotnet publish -c Release -r linux-x64 /p:PackAsTool=false Source/Boogie.sln
          dotnet publish -c Release -r win-x64 /p:PackAsTool=false Source/Boogie.sln
          dotnet publish -c Release -r osx-x64 /p:PackAsTool=false Source/Boogie.sln
        if: matrix.os == 'ubuntu-latest'

      - name: Prepare publication
        run: |
          mv boogie/Source/BoogieDriver/bin/Release/net5.0/linux-x64/publish/ binaries-linux
          mv binaries-linux/BoogieDriver binaries-linux/Boogie
          zip boogie-linux.zip binaries-linux/*

          mv boogie/Source/BoogieDriver/bin/Release/net5.0/win-x64/publish/ binaries-win
          mv binaries-win/BoogieDriver.exe binaries-win/Boogie.exe
          zip boogie-win.zip binaries-win/*

          mv boogie/Source/BoogieDriver/bin/Release/net5.0/osx-x64/publish/ binaries-osx
          mv binaries-osx/BoogieDriver binaries-osx/Boogie
          zip boogie-osx.zip binaries-osx/*
        if: matrix.os == 'ubuntu-latest'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.BOOGIE_BRANCH }}
          files: |
            boogie-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: matrix.os == 'ubuntu-latest'
